<?php

use Application\Form\KleoForm;

$formulario = $this->formulario;
$formulario->prepare();

$formulario->setAttribute(KleoForm::stringAction, '/cadastroResponsavelAtualizar');
echo $this->form()->openTag($formulario);
echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
echo $this->formHidden($formulario->get(KleoForm::inputId));
?>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix signUp">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Atualização</h3></div>
          <div class="panel-body">
            <form action="/cadastroResponsavelFinalizar" method="POST" role="form">
              <?php
              echo $this->inputFormulario(KleoForm::traducaoNome, $formulario->get(KleoForm::inputNome));
              echo $this->inputFormulario(KleoForm::traducaoDDD, $formulario->get(KleoForm::inputDDD), 3);
              echo $this->inputFormulario(KleoForm::traducaoTelefone, $formulario->get(KleoForm::inputTelefone), 9);
              echo $this->inputFormulario(KleoForm::traducaoEmail, $formulario->get(KleoForm::inputEmail));
              echo $this->inputFormulario(KleoForm::traducaoCPF, $formulario->get(KleoForm::inputCPF));
              echo $this->inputFormulario(KleoForm::traducaoDia, $formulario->get(KleoForm::inputDia), 4);
              echo $this->inputFormulario(KleoForm::traducaoMes, $formulario->get(KleoForm::inputMes), 4);
              echo $this->inputFormulario(KleoForm::traducaoAno, $formulario->get(KleoForm::inputAno), 4);


              echo $this->inputFormulario(KleoForm::traducaoNomeFantasia, $formulario->get(KleoForm::inputNomeFantasia));
              echo $this->inputFormulario(KleoForm::traducaoRazaoSocial, $formulario->get(KleoForm::inputRazaoSocial));
              echo $this->inputFormulario(KleoForm::traducaoCNPJ, $formulario->get(KleoForm::inputCNPJ));
              echo $this->inputFormulario(KleoForm::traducaoDDDEmpresa, $formulario->get(KleoForm::inputDDDEmpresa), 3);
              echo $this->inputFormulario(KleoForm::traducaoTelefoneEmpresa, $formulario->get(KleoForm::inputTelefoneEmpresa), 9);
              echo $this->inputFormulario(KleoForm::traducaoEmailEmpresa, $formulario->get(KleoForm::inputEmailEmpresa));
              echo $this->inputFormulario(KleoForm::traducaoNumeroLojas, $formulario->get(KleoForm::inputNumeroLojas));
              echo $this->botao('Atualizar', $this->funcaoOnClick('this.form.submit()'));
              ?>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<?php
echo $this->form()->closeTag();