<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ToNoShop')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/colors/default.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('plugins/rs-plugin/css/settings.css'))
                ->prependStylesheet($this->basePath('plugins/selectbox/select_option1.css'))
                ->prependStylesheet($this->basePath('plugins/owl-carousel/owl.carousel.css'))
                ->prependStylesheet($this->basePath('plugins/jquery-ui/jquery-ui.css'))
                ->prependStylesheet($this->basePath('plugins/bootstrapBigbag/css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('plugins/font-awesome/css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/colors/default.css'))
                ->prependStylesheet('https://fonts.googleapis.com/css?family=Oxygen:400,300,700');
        ?>
    </head>
    <body>
        <!-- HEADER -->
        <div class="header clearfix">

            <!-- TOPBAR -->
            <div class="topBar">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 col-xs-12">
                            <ul class="list-inline pull-right top-right">
                                <li class="account-login">
                                  <span>
                                     <a data-toggle="modal" href='/cadastroResponsavel'>Seja Parceiro</a>
                                     - <a data-toggle="modal" href='/cadastroEmpresa'>Cadastro Empresa</a>
                                  </span>
                              </li>
                            </ul>
                        </div>
                    </div>
                </div>    
            </div>

            <!-- NAVBAR -->
            <nav class="navbar navbar-main navbar-default" role="navigation">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="index-v1.html"><img src="img/logo.png" alt="logo"></a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse navbar-ex1-collapse">            
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown active">
                                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Home</a>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div>
            </nav>

        </div>

       
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->

        <!-- FOOTER -->
        <div class="footer clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-sm-2 col-xs-12">
                        <div class="footerLink">
                            <h5>Accessories</h5>
                            <ul class="list-unstyled">
                                <li><a href="#">Body care </a></li>
                                <li><a href="#">Chambray </a></li>
                                <li><a href="#">Floral </a></li>
                                <li><a href="#">Rejuvination </a></li>
                                <li><a href="#">Shaving </a></li>
                                <li><a href="#">Toilette </a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-2 col-xs-12">
                        <div class="footerLink">
                            <h5>BRANDS</h5>
                            <ul class="list-unstyled">
                                <li><a href="#">Barbour </a></li>
                                <li><a href="#">Brioni </a></li>
                                <li><a href="#">Oliver Spencer</a></li>
                                <li><a href="#">Belstaff</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-2 col-xs-12">
                        <div class="footerLink">
                            <h5>Accessories</h5>
                            <ul class="list-unstyled">
                                <li><a href="#">Body care </a></li>
                                <li><a href="#">Chambray </a></li>
                                <li><a href="#">Floral </a></li>
                                <li><a href="#">Rejuvination </a></li>
                                <li><a href="#">Shaving </a></li>
                                <li><a href="#">Toilette </a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-2 col-xs-12">
                        <div class="footerLink">
                            <h5>Get in Touch</h5>
                            <ul class="list-unstyled">
                                <li>Call us at (555)-555-5555</li>
                                <li><a href="mailto:support@iamabdus.com">support@iamabdus.com</a></li>
                            </ul>
                            <ul class="list-inline">
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                                <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-4 col-xs-12">
                        <div class="newsletter clearfix">
                            <h4>Newsletter</h4>
                            <h3>Sign up now</h3>
                            <p>Enter your email address and get notified about new products. We hate spam!</p>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
                                <a href="#" class="input-group-addon" id="basic-addon2">go <i class="glyphicon glyphicon-chevron-right"></i></a>
                            </div>
                        </div>  
                    </div>
                </div>
            </div>
        </div>

        <!-- COPY RIGHT -->
        <div class="copyRight clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-sm-7 col-xs-12">
                        <p>&copy; 2016 Copyright Bigbag Store Bootstrap Template by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
                    </div>
                    <div class="col-sm-5 col-xs-12">
                        <ul class="list-inline">
                            <li><img src="img/home/footer/card1.png"></li>
                            <li><img src="img/home/footer/card2.png"></li>
                            <li><img src="img/home/footer/card3.png"></li>
                            <li><img src="img/home/footer/card4.png"></li>
                        </ul> 
                    </div>
                </div>
            </div>
        </div>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/custom.js'))
                ->prependFile($this->basePath('plugins/countdown/jquery.syotimer.js'))
                ->prependFile($this->basePath('plugins/selectbox/jquery.selectbox-0.1.3.min.js'))
                ->prependFile($this->basePath('plugins/owl-carousel/owl.carousel.js'))
                ->prependFile($this->basePath('plugins/rs-plugin/js/jquery.themepunch.revolution.min.js'))
                ->prependFile($this->basePath('plugins/rs-plugin/js/jquery.themepunch.tools.min.js'))
                ->prependFile($this->basePath('plugins/bootstrapBigbag/js/bootstrap.min.js'))
                ->prependFile($this->basePath('plugins/jquery-ui/jquery-ui.js'))
                ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js');
        echo $this->inlineScript();
        ?>
    </body>
</html>
